name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Build
      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn install --immutable

      - name: Build the file
        run: yarn build

      # Upload build artifact to the release as an asset.
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/config-template-card.js
          asset_name: config-template-card.js
          tag: ${{ github.ref }}
          overwrite: true